version: 2.1

jobs:

  # Deploy to production environment
  deploy_production:
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          name: prepare
          command: |
            apt update; apt install -y git curl zip unzip openssh-client openssh-server
      - checkout
      - run:
          name: deploy
          command: |
            ssh $VM_USER@$VM_IPADDRESS "cd docker && docker-compose pull frontend && docker-compose pull backend && docker-compose up --force-recreate --no-deps -d frontend backend"
  

workflows:
  build_and_push:
    jobs:
      - deploy_production:
          context: context
          filters:
            tags:
              only: /^stable.*$/
