
global:
  scrape_interval:     15s # fréquence à laquelle Prometheus scrape les cibles par défaut
  evaluation_interval: 15s # fréquence à laquelle Prometheus évalue les règles d'alerte par défaut

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['85.31.239.78:9090'] # cible à scraper : le serveur Prometheus lui-même

  - job_name: 'tiptopgame'
    static_configs:
      - targets: ['85.31.239.78'] # cible à scraper : votre application exposant des métriques
